config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root "pages#index"

  resources :articles do
      member do
        get "like", to: "articles#vote"
        # Only uncomment below line if downvoting is implemented
        get "dislike", to: "articles#downvote"
      end
    end
  resources :pages

  get "/randomize", to: "articles#randomize"
  get '/search' => "articles#search"
  get '/about' => "pages#about"
  get '/relax' => "pages#relax"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "/signup" => "users#new", :as => "signup"  
  get "/me" => "users#show", :as => "me"
  resources :users  
  resources :sessions
  resources :links

  get 'docs/template' => "docs#template"
  get 'docs/links' => "docs#links"
  get 'docs/article' => "docs#article"
  get 'docs/link-from-article' => "docs#link_from_article"
  get 'docs/links-from-category' => "docs#link_from_cat"
  get 'docs/page' => "docs#doc_from_page"

  get '/api/users/login' => "users#api_auth"
  get '/api/users/show' => "users#api_show"
  get '/api/users/new' => "users#api_new"
  get '/api/categories' => "apis#categories"

  get '/random' => "articles#random"
  get '/:id' => "articles#show", :as => "article_show"

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, 
            :content,
            :link, 
            presence: true
            
  validates :link, uniqueness: true
  acts_as_votable

       
  def self.search(search)
    if search
      # where(["title LIKE ? OR content[0] LIKE ?", "%#{search}%", "%#{search}%"])
      where("lower(title) LIKE lower('% #{search} %') 
             OR lower(link) LIKE lower('%#{search}%')
             OR lower(content[1]) LIKE lower('% #{search} %') 
             OR lower(content[2]) LIKE lower('% #{search} %') 
             OR lower(content[3]) LIKE lower('% #{search} %')
             OR lower(content[4]) LIKE lower('% #{search} %')
             OR lower(title) LIKE lower('%#{search}%') 
             OR lower(content[1]) LIKE lower('%#{search}%') 
             OR lower(content[2]) LIKE lower('%#{search}%') 
             OR lower(content[3]) LIKE lower('%#{search}%')
             OR lower(content[4]) LIKE lower('%#{search}%')")
    else
      none
    end
  end   
  def self.from_ft
    where("link LIKE '%ft.com%'").count
  end         
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		if params[:page]
			page = params[:page]	
		else 
			page = 1
		end
    if params[:per_page] 
      per_page = params[:per_page]
    else
      per_page = 15
    end
    @articles = Article.order(:cached_votes_score => :desc).paginate(:page => page, :per_page => per_page)
		@page = page
		@title = "Articles - "
    respond_to do |format|
      format.json  { render :json => @articles } # don't do msg.to_json
      format.html 
    end
	end

	def show
		@article = Article.find(params[:id])
		@title = @article.title
    @link = Link.new()
    @link.article_title = @article.title
    if @article.link.scan(/\/([^"]*)\./)[0][0].include? "www."
      @link.website_title = "Cabretio"
    else
      @link.website_title = @article.link.scan(/\/([^"]*)\./)[0][0]
    end
    @link.url = "#{request.protocol}#{request.host_with_port}/#{@article.id}"
    respond_to do |format|
      format.json  { render :json => @article } # don't do msg.to_json
      format.html 
    end
	end
	
	def search
		if params[:page]
			@page = params[:page]	
  		@title = "Search Results - "
		else 
			@page = 1
      @title = "Search - "
		end
    if params[:per_page] 
      per_page = params[:per_page]
    else
      per_page = 15
    end
		@articles = Article.search(params[:search]).paginate(:page => @page, :per_page => per_page)
		@count = @articles.count
    respond_to do |format|
      format.json  { render :json => @articles } # don't do msg.to_json
      format.html 
    end
	end
  
  def random 
    @art = Article.order("RANDOM()").first
    redirect_to article_path(@art)
  end

  require 'open-uri'
  def create
    if !current_user
      flash[:danger] = "HEY! You need to be signed in to do that"
      redirect_to login_path
      return
    end
    begin  
      page = Nokogiri::HTML(open(permitted_params))
      source = open(permitted_params).read
    rescue => e
      flash[:danger] = "HEY! That's not a real url"
      redirect_to root_path
      return
    end
    content = Readability::Document.new(source).content
    pTags = Nokogiri::HTML(content).css("p")
    title = page.css("h1")[0].text.strip
    tags = []
    pTags.each do |tag| 
      tags.push(tag.text.strip)
    end
    @article = Article.new
    @article.title = title
    @article.content = tags
    @article.link = permitted_params
    # if params[:create_link] == "1"
    #   puts "YES"
    #   @user = current_user
    #   link = @article.link.scan(/\.([^"]*)\./)
    #   if link.empty?
    #     link = @article.link.scan(/\/([^"]*)\./)
    #   end
    #   puts link.count
    #   @link = @user.links.new(:website_title => link[0][0],
    #                           :article_title => @article.title,
    #                           :date_accessed => DateTime.now(),
    #                           :user => @user,
    #                           :url => @article.link)
    #   if @link.save!
    #     flash[:info] = "psst, we also added this to your links :)"
    #   end
    # end
    if @article.save
      flash[:success] = "Awesome, you've created a new article!"
      redirect_to article_path(@article)
    else
        render "new"
    end
  end
  def new 
  end
  
  def randomize
		if params[:page]
			page = params[:page]	
		else 
			page = 1
		end
    @articles = Article.order("RANDOM()").paginate(:page => page, :per_page => 15)
		@page = page
		@title = "Articles - "
  end

  def vote
    @article = Article.find(params[:id])
    if !current_user
      flash[:danger] = "You need to be logged in to like a post"
      session[:return_to_url] = like_article_path(@article)
      redirect_to login_path
    elsif current_user.voted_up_on? @article
      flash[:warning] = "You've already liked this article, try to like another one"
      redirect_to article_path(@article)
    elsif @article.liked_by current_user
      flash[:success] = "You liked this article"
      redirect_to article_path(@article)
    end
  end

  def downvote
    @article = Article.find(params[:id])
    if !current_user
      flash[:danger] = "You need to be logged in to like a post"
      session[:return_to_url] = dislike_article_path(@article)
      redirect_to login_path
    elsif current_user.voted_down_on? @article
      flash[:warning] = "You've already liked this article, try to like another one"
      redirect_to article_path(@article)
    elsif @article.disliked_by current_user
      flash[:success] = "You disliked this article"
      redirect_to article_path(@article)
    end
  end	

  private
    def permitted_params
      params.require(:link)
    end
end

app/views/articles/_pagination.html.slim
- unless mobile_device?
	= will_paginate @articles, renderer: BootstrapPagination::Rails, :inner_window => 1, :outer_window => 1
- else
	ul.pager
		- if @articles.current_page > @articles.total_pages
			li.previous.pull-left
				= link_to "Previous", "#{articles_path}?page=#{@articles.current_page-1}", :class => "previous pull-left"
		- else 
			li.previous.pull-left.disabled
				a
					| Previous
		li
			= @articles.current_page
			| /
			= @articles.total_pages
		- if @articles.current_page < @articles.total_pages
			li.next.pull-right
				= link_to "Next", "#{articles_path}?page=#{@articles.current_page+1}"
		- else 
			li.next.pull-right.disabled
				a
					| Next

app/views/articles/_search.html.slim
div.row
	= form_tag search_path, :class => "form-horizontal", :method => 'get' do
	    div.col-sm-10
      		= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search all articles"
	    div.col-sm-2
	      = submit_tag "Search", :name => nil, :class=>"btn btn-success btn-md pull-right"

app/views/articles/_voteButtons.html.slim
- thumbUp = icon('thumbs-up')
- thumbDown = icon('thumbs-down')
- if !current_user or !current_user.voted_for? article
	=' link_to like_article_path(article), :method => :put, :class => "btn btn-success"
		= thumbUp
	.btn.btn-default.btn-sm.disabled = (article.get_likes.size - article.get_dislikes.size)
	=' link_to dislike_article_path(article), :method => :put, :class => "btn btn-danger"
		= thumbDown
- elsif current_user and current_user.voted_up_on? article
	.btn.btn-default.disabled = thumbUp
	.btn.btn-default.btn-sm.disabled = (article.get_likes.size - article.get_dislikes.size)
	=' link_to dislike_article_path(article), :method => :put, :class => "btn btn-danger"
		= thumbDown
- else
	=' link_to like_article_path(article), :method => :put, :class => "btn btn-success"
		= thumbUp
	.btn.btn-default.btn-sm.disabled = (article.get_likes.size - article.get_dislikes.size)
	.btn.btn-default.disabled = thumbDown

app/views/articles/index.html.slim
div.row
	div.col-xs-12
    .wrap
      - if @page == 1 or params[:page] == "1"
        h1.text-center This is Cabretio
        p.text-center
          ' Your source for researching anything related to anything. All the articles are provided by you! We currently have 
          =' human_num(@articles.count)
          | articles and ever growing!
	

      / h3#search Search
      = render "search"
      p 
        ' Want to see random articles?
        = link_to "randomize", randomize_path, :class => "btn btn-sm btn-success"

      - @articles.each do |article|
        .row 
          .col-sm-11
            h5 = link_to article_show_path(article)
              = article.title
            p  
              =' truncate(article.content.first, :length => 200, :omission => "...") do
              = link_to "More", article_show_path(article)
          .col-sm-1
            .pull-right.index-vote-count
              .btn-group-vertical.pull-right role="group" aria-label="..."
                = render "voteButtons", :article => article
    .text-center
        = render "pagination"

app/views/articles/new.html.slim
.wrap
	h3
		| Add an Article
	= form_tag :action => "create", :controller => "articles", :method => "post"
		= text_field_tag :link,"", :class => "form-control", :placeholder => "Link"
		= submit_tag "Create", :name => nil, :class=>"btn btn-success btn-md"

app/views/articles/randomize.html.slim
.wrap
	div.col-xs-12
		h3 Search
		= render "search"
		p 
			' Want to see the popular articles?
			= link_to "popularize", articles_path, :class => "btn btn-xs btn-info"
		
	div.col-xs-12
		- @articles.each do |article|
			.row 
				.col-xs-10.col-sm-11
					h5 = link_to article_show_path(article)
						= article.title
					p  = article.content.first
				.col-xs-2.col-sm-1
					.pull-right.index-vote-count
						.btn-group-vertical role="group" aria-label="..."
							= render "voteButtons", :article => article

	div.row
		div.text-center
			' Roll some more articles?
			= link_to "randomize", randomize_path, :class => "btn btn-xs btn-info"

app/views/articles/search.html.slim
.wrap
    div.row
        div.col-xs-12
          	h3 Search
          	= render "search"
    div.row
        div.col-xs-12
            - if @count == 0 && params[:search]
                p 
                    | Sorry we couldn't find any articles with that search query, please try a different search.
            - elsif @count > 100
                p 
                    | There are a lot of results, we suggest refinings your query.
    div.row
        div.col-xs-12
            p 
                ' Total results:
                = human_num(@count)
            - @articles.each do |article|
    					.row 
    						.col-xs-10.col-sm-11
    							h3 = link_to article_show_path(article)
    								= article.title
                                - pass = false
    							- article.content.each do |cont|
    								- if cont.downcase[" #{params[:search]} ".downcase]
    									p = cont
                                        - pass = true
    									- break
                                - if !pass
                                    p = article.content.first
    						.col-xs-2.col-sm-1
    							.pull-right.index-vote-count
    								.btn-group-vertical role="group" aria-label="..."
    									= render "voteButtons", :article => article

.pagination-container
 	= render "pagination"

javascript:
  $(".content p, a ").highlight("#{params[:search]}", { wordsOnly: true });

app/views/articles/show.html.slim
.wrap
	h1 = @article.title
	.row
		.col-sm-10
			small.subtitle 
				' Original location:
				= link_to truncate(@article.link, :length => 50, :omission => "..."), @article.link, :target => "_blank"
		.col-sm-2
			p
				a.btn.btn-sm.btn-info.doc-download.pull-right href="#" data-article="#{@article.id}" data-url="article" title="Download this article into a word doc"
					' download
					= icon('file-word-o')
	hr
	- @article.content.each do |p|
		p = p

	div.panel.panel-default
				div.panel-heading
					' Citation for Works Cited
					span.pull-right 
						.btn-group role="group" aria-label="..."
							= render "voteButtons", :article => @article
						- text = icon('save', '', class: 'save')
						a.btn.btn-sm.btn-info href="#" data-toggle="modal" data-target="#newLinkModal"
							= text
						a.btn.btn-sm.btn-info.doc-download href="#" data-article="#{@article.id}" data-url="link-from-article" title="Download this citation into a word doc"
							= icon('file-word-o', '', class: 'save')
				div.panel-body
					= citation(@article.title, "Cabretio", Date.today, "#{request.protocol}#{request.host_with_port}#{request.fullpath}")
	#disqus_thread
	noscript
		| Please enable JavaScript to view the 
		a href="http://disqus.com/?ref_noscript"
			| comments powered by Disqus.
	.tip#highlightTooltip
		.header
			| Hey I'm a tooltip
			button.close#closeTooltip type="button"
				span aria-hidden="true" &times;
				span class="sr-only" close
		.body
			| Try highlighting a word to get the definition of the word.
	javascript:
		$( "p" )
	  	.mouseup(function() {
	  		console.log($.selection());
	  	});
		var showModal = getCookie("showHighlightPopover");
		if (showModal == "") {
			$(".tip").show();
		} else {
			$(".tip").hide();
		}
		$("#closeTooltip").click(function() {
			$(".tip").hide();
			setCookie("showHighlightPopover", "no", 365);
		});

	  	var disqus_shortname = 'cabretio'; // required: replace example with your forum shortname

	    /* * * DON'T EDIT BELOW THIS LINE * * */
	    (function() {
	        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	    })();
		