config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root "pages#index"

  resources :articles do
      member do
        get "like", to: "articles#vote"
        # Only uncomment below line if downvoting is implemented
        get "dislike", to: "articles#downvote"
      end
    end
  resources :pages

  get "/randomize", to: "articles#randomize"
  get '/search' => "articles#search"
  get '/about' => "pages#about"
  get '/relax' => "pages#relax"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "/signup" => "users#new", :as => "signup"  
  get "/me" => "users#show", :as => "me"
  resources :users  
  resources :sessions
  resources :links

  get 'docs/template' => "docs#template"
  get 'docs/links' => "docs#links"
  get 'docs/article' => "docs#article"
  get 'docs/link-from-article' => "docs#link_from_article"
  get 'docs/links-from-category' => "docs#link_from_cat"
  get 'docs/page' => "docs#doc_from_page"

  get '/api/users/login' => "users#api_auth"
  get '/api/users/show' => "users#api_show"
  get '/api/users/new' => "users#api_new"
  get '/api/categories' => "apis#categories"

  get '/random' => "articles#random"
  get '/:id' => "articles#show", :as => "article_show"

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  before_validation :downcase_email, on: 'create'

  has_many :links

  validates :email, uniqueness: true

  validates :email, :password, presence: true
  
  acts_as_voter

  private
	  def downcase_email
	    self.email = self.email.downcase
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		if current_user
    		@user = current_user
    		@links = current_user.links.order("created_at DESC")
    		@title = "Your Page - "
        @categories = current_user.links.select('category').uniq!
    	else
    		flash[:danger] = "You need to be logged in to see that page!"
    		redirect_to login_path
    	end
  	end

  	def new
    	@user = User.new
      @title = "Sign Up - "
  	end

  	def create
    	@user = User.new(permitted_params)
    	if @user.save
        UserMailer.welcome_email(@user).deliver
		    auto_login(@user)
		    flash[:success] = "Thanks for signing up!"
		    redirect_to root_path
    	else
      		render :new
    	end
  	end 


    def api_auth
      
      if params[:key] != Rails.application.secrets.api_key
        render :json => "no"
        return
      end
      user = login(params[:email], params[:password], false)
      if user 
        # Login succeeded
        logout
        render :json => "ok"
      else
        # Login Failed
        render :json => "no"
      end
    end
    def api_show 
      if params[:key] != Rails.application.secrets.api_key
        render :json => "no"
        return
      end
      user = User.find_by_email(params[:email])
      render :json => user.links.order("category")
    end

    def api_new
      @user = User.new(permitted_params)
      if params[:key] != Rails.application.secrets.api_key
        render :json => "no"
        return
      end
      if @user.save 
        render :json => "ok"
      else
        render :json => "no"
      end
    end 


private
  	def permitted_params
    	params.require(:user).permit(:email,
        	                         :password)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.slim
.wrap
	h3
		| Works Cited

	- if @links.count > 0
		p
			a.btn.btn-sm.btn-info.doc-download href="#" data-links="all" data-url="links" title="Download all your links into a word doc"
				= icon('file-word-o')
		- @categories.each_with_index do |cat, index|
			= link_to cat.category, "##{cat.category}", :class => "scroll"
			span 
				=  " | " unless index == @categories.count - 1 
		- currentCat = @links.first.category
		- @links.each_with_index do |link, index|
			- if link.category != currentCat or index == 0
				- currentCat = link.category
				h5 id="#{currentCat}"
					= currentCat
					.pull-right
						a.btn.btn-sm.btn-info.doc-download href="#" data-links="#{link.category}" data-url="links-from-category" title="Download this article into a word doc"
							' Download 
							=' link.category
							' citations
							= icon('file-word-o', '', class: 'save')
			div.panel.panel-default
				div.panel-heading
					= link_to link.article_title, link.url
					span.pull-right 
						- text = icon('trash', '', class: 'trash')
						/ = link_to text, link_path(link), :method => :put
						button data-link-id=link.id class="link-destroy btn btn-sm btn-danger"
							= text
					span.pull-right
						= link_to edit_link_path(link), :class => "btn btn-sm btn-info" do
							= icon('pencil', '', class: 'edit')
						a.btn.btn-sm.btn-info.doc-download href="#" data-links="#{link.id}" data-url="links" title="Download this article into a word doc"
							= icon('file-word-o', '', class: 'save')
				div.panel-body
					= citation(link.article_title, link.website_title, link.date_accessed, link.url)
	- else
		button.btn.btn-sm.btn-info data-toggle="modal" data-target="#newLinkModal"
			| You need some citations