config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root "pages#index"

  resources :articles do
      member do
        get "like", to: "articles#vote"
        # Only uncomment below line if downvoting is implemented
        get "dislike", to: "articles#downvote"
      end
    end
  resources :pages

  get "/randomize", to: "articles#randomize"
  get '/search' => "articles#search"
  get '/about' => "pages#about"
  get '/relax' => "pages#relax"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "/signup" => "users#new", :as => "signup"  
  get "/me" => "users#show", :as => "me"
  resources :users  
  resources :sessions
  resources :links

  get 'docs/template' => "docs#template"
  get 'docs/links' => "docs#links"
  get 'docs/article' => "docs#article"
  get 'docs/link-from-article' => "docs#link_from_article"
  get 'docs/links-from-category' => "docs#link_from_cat"
  get 'docs/page' => "docs#doc_from_page"

  get '/api/users/login' => "users#api_auth"
  get '/api/users/show' => "users#api_show"
  get '/api/users/new' => "users#api_new"
  get '/api/categories' => "apis#categories"

  get '/random' => "articles#random"
  get '/:id' => "articles#show", :as => "article_show"

end

app/views/pages/about.html.slim
.wrap
  h1 
      | About Cabretio

  p
    | Cabretio is a research platform created to provide resources for students  in their learning endeavors. 
  p
    | The base system includes 
    =' @ft_count
    | articles provided by 
    = link_to "Financial Times", "http://www.ft.com"
    | . In the future we hope to allow students to host any articles in our system.
  p
    | Currently, Cabretio lets students read over 
    =' @count
    | articles, save these articles to view later, and cite the articles in their research bibliographies. 
  p
    | These are the basics for student research needs, but it's not enough.
  p
    | For students to truly succeed, the tools they use need to be the best; that's what the Cabretio is here for.
  p
    | We have big goals; we can't share all of them with you right now, but they are on the horizon, and they will be here soon.

app/views/pages/index.html.slim
div#particles-js data-count=@node_count
div.vertAlign
    h3.white.text-center
       	' Search over 
		=' human_num(@count)
    	| Articles
    = form_tag search_path, :class => "form-horizontal", :method => 'get' do
  		.home-form-wrap
	  		= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search all articles"
	      	= submit_tag "Search", :name => nil, :class=>"btn btn-success btn-md home-submit"
    .row
	    .col-xs-12
		    p.white.text-center
		    	=' link_to "About Cabretio", about_path
				' |
				=' link_to "Articles", articles_path
				' |
				=' link_to "Feeling Stressed", relax_path

javascript:
	particlesJS('particles-js', {
	  particles: {
	    color: '#fff',
	    shape: 'circle', // "circle", "edge" or "triangle"
	    opacity: 0.75,
	    size: 2,
	    size_random: true,
	    nb: $('#particles-js').data('count'),
	    anim: {
	      enable: true,
	      speed: 0.5
	    }
	  },
	  interactivity: {
	    enable: true,
	    mouse: {
	      distance: 125
	    },
	    detect_on: 'canvas', // "canvas" or "window"
	    mode: 'grab',
	    line_linked: {
	      enable_auto: true,
	      distance: 100,
	      color: '#fff',
	      opacity: 1,
	      width: 1,
	      condensed_mode: {
	        enable: true,
	        rotateX: 600,
	        rotateY: 600
	      }
	    },
	    events: {
	      onclick: {
	        enable: false
	      }
	    }
	  },
	  /* Retina Display Support */
	  retina_detect: true
	});

app/views/pages/relax.html.slim
css:
	.vertAlign, h1, p {
		color: white !important;
	}

div.vertAlign.text-center
	h1
		| We get it, research is tough, take a break, relax, and enjoy some cute puppies.
	p 
		| Press any key or refresh the page, for new puppies