config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root "pages#index"

  resources :articles do
      member do
        get "like", to: "articles#vote"
        # Only uncomment below line if downvoting is implemented
        get "dislike", to: "articles#downvote"
      end
    end
  resources :pages

  get "/randomize", to: "articles#randomize"
  get '/search' => "articles#search"
  get '/about' => "pages#about"
  get '/relax' => "pages#relax"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "/signup" => "users#new", :as => "signup"  
  get "/me" => "users#show", :as => "me"
  resources :users  
  resources :sessions
  resources :links

  get 'docs/template' => "docs#template"
  get 'docs/links' => "docs#links"
  get 'docs/article' => "docs#article"
  get 'docs/link-from-article' => "docs#link_from_article"
  get 'docs/links-from-category' => "docs#link_from_cat"
  get 'docs/page' => "docs#doc_from_page"

  get '/api/users/login' => "users#api_auth"
  get '/api/users/show' => "users#api_show"
  get '/api/users/new' => "users#api_new"
  get '/api/categories' => "apis#categories"

  get '/random' => "articles#random"
  get '/:id' => "articles#show", :as => "article_show"

end

app/views/layouts/_add-forms.html.slim
div class="modal fade" id="newArticle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
	div class="modal-dialog"
		= form_tag :action => "create", :controller => "articles", :method => "post"
			div class="modal-content"
				div class="modal-header"
					button type="button" class="close" data-dismiss="modal"
						span aria-hidden="true" &times;
						span class="sr-only" close
					h4 class="modal-title" id="myModalLabel"
						| Add an Article
				.modal-body
					= text_field_tag :link,"", :class => "form-control", :placeholder => "Link"
					.checkbox
						label	
							= check_box_tag :create_link
							| Add to your links
				.modal-footer
					button type="button" class="btn btn-danger" data-dismiss="modal"
						| Cancel
					= submit_tag "Create", :name => nil, :class=>"btn btn-success btn-md"
div class="modal fade" id="newLinkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
	div class="modal-dialog"
		div class="modal-content"
			.modal-header
				button type="button" class="close" data-dismiss="modal"
					span aria-hidden="true" &times;
					span class="sr-only" close
				h4 class="modal-title" id="myModalLabel"
					| New Citation
			.modal-body
				= simple_form_for(@link, html: { class: 'form-vertical' }) do |f|
					.form-group
						= f.input :article_title, :placeholder => "Article Title", :label => "Article Title", :input_html => { :class => "form-control"}
					.form-group
						= f.input :website_title, :placeholder => "Website Title", :label => "Website Title", :input_html => { :class => "form-control" }
					.form-group
						= f.input :url, :placeholder => "Website URL", :label => "Website URL", :input_html => { :class => "form-control" }
					.form-group
						= f.input :date_accessed, :placeholder => "Date Accessed", :label => "Date Accessed", :input_html => { :class => "", :value => DateTime.now }
					.form-group
						= f.submit :class =>"btn btn-sm btn-success", :value => "Create New Link"

app/views/layouts/_form.html.slim
div class="modal fade" id="newArticle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
	div class="modal-dialog"
		= form_tag :action => "create", :controller => "articles", :method => "post"
			div class="modal-content"
				div class="modal-header"
					button type="button" class="close" data-dismiss="modal"
						span aria-hidden="true" &times;
						span class="sr-only" close
					h4 class="modal-title" id="myModalLabel"
						| Add an Article
				.modal-body
					= text_field_tag :link,"", :class => "form-control", :placeholder => "Link"
					.checkbox
						label	
							= check_box_tag :create_link
							| Add to your links
				.modal-footer
					button type="button" class="btn btn-danger" data-dismiss="modal"
						| Cancel
					= submit_tag "Create", :name => nil, :class=>"btn btn-success btn-md"
div class="modal fade" id="newLinkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
	div class="modal-dialog"
		div class="modal-content"
			.modal-header
				button type="button" class="close" data-dismiss="modal"
					span aria-hidden="true" &times;
					span class="sr-only" close
				h4 class="modal-title" id="myModalLabel"
					| New Citation
			.modal-body
				= simple_form_for(@link, html: { class: 'form-vertical' }) do |f|
					.form-group
						= f.input :article_title, :placeholder => "Article Title", :label => "Article Title", :input_html => { :class => "form-control"}
					.form-group
						= f.input :website_title, :placeholder => "Website Title", :label => "Website Title", :input_html => { :class => "form-control" }
					.form-group
						= f.input :url, :placeholder => "Website URL", :label => "Website URL", :input_html => { :class => "form-control" }
					.form-group
						= f.input :date_accessed, :placeholder => "Date Accessed", :label => "Date Accessed", :input_html => { :class => "", :value => DateTime.now }
					.form-group
						= f.submit :class =>"btn btn-sm btn-success", :value => "Create New Link"

app/views/layouts/application.html.slim
html
	head
	  title= "#{@title} Cabretio"
    link href='http://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  = favicon_link_tag 'favicon.ico'
	  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	  = javascript_include_tag src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
	  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
	  = csrf_meta_tags
	body 
		div class=@body
	
		nav.navbar.no-scroll.navbar-default.navbar-fixed-top role="navigation" 
			.container
				.navbar-header
					button.navbar-toggle.collapsed data-target=".collapse" data-toggle="collapse" type="button" 
						span.sr-only Toggle navigation
						span.icon-bar
		        		span.icon-bar
		        		span.icon-bar
		      		a.navbar-brand href=root_path  Cabretio
		    	.navbar-collapse.collapse
		      		ul.nav.navbar-nav
		        		li
							= link_to "Home", root_path
		          		li
		          			= link_to "Articles", articles_path
		          		li	
		          			= link_to "About", about_path
		          	- if current_user	
		          		ul.nav.navbar-nav.navbar-right
		          			li
		          				= link_to current_user.email, me_path
		          			li
		          				= link_to "Logout", logout_path
					-else 
						ul.nav.navbar-nav.navbar-right
							li	
			          			button.btn.btn-sm.btn-success.nav-link data-toggle="modal" data-target="#signupModal"
			          				| Sign Up

			          		li	
			          			/ = link_to "Login", login_path
			          			button.btn.btn-sm.btn-success.nav-link data-toggle="modal" data-target="#loginModal"
			          				| Login
          				= render "extras/loginmodals"
	

		div.container#primary-content
			div.row
        div.col-xs-12.col-sm-8.col-sm-offset-2
          	- if flash.count > 0
            	- flash.each do |name, msg|
              		div class="alert alert-dismissable alert-#{name}"
                		<button type="button" class="close" data-dismiss="alert">×</button>
                		= raw(msg)
        	= yield 
		-if current_user
			.info-wrap
			  .fab
			    | +
			  .pane
			    .item href="#" data-toggle="modal" data-target="#newLinkModal"
			      | Create Citation
			    .item href="#" data-toggle="modal" data-target="#newArticle"
			      | Add Article		
			= render "extras/addforms"
		= analytics_init if Rails.env.production?